version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin  
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin  
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  app:
    depends_on:
      - mongodb
    build: ./web-app
    restart: unless-stopped
    ports:
      - 4000:4000
    environment:
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=tweety
      - DB_PORT=8081
    stdin_open: true
    tty: true
    